# -*- coding: utf-8 -*-
"""Front Model 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h5mpgp0bKit0gYbA-1FxOC3tMjccy68J
"""

import joblib
import gradio as gr
import numpy as np

# Define the path to your model
model_path = '/content/random_forest_regressor_model.joblib'

# Load the model
try:
    model = joblib.load(model_path)
    print(f"Model loaded successfully from {model_path}")
except FileNotFoundError:
    print(f"Error: Model file not found at {model_path}")
    # You might want to handle this error more gracefully or exit
    model = None # Set model to None if loading fails

# Define a prediction function that the Gradio interface will call
# This function assumes your model takes a fixed number of numerical inputs.
# You will need to adjust the number of arguments (e.g., feature1, feature2, etc.)
# and how they are processed based on your model's actual input requirements.
# For a RandomForestRegressor, it typically expects a 2D array-like input.

def predict_output(feature1, feature2, feature3, feature4, feature5):
    if model is None:
        return "Model not loaded. Cannot make prediction."

    # Create a numpy array from the input features
    # The model expects a 2D array, even for a single prediction
    features = np.array([[feature1, feature2, feature3, feature4, feature5]])

    try:
        prediction = model.predict(features)
        return f"Predicted Value: {prediction[0]:.2f}"
    except Exception as e:
        return f"Error during prediction: {e}"

# Create the Gradio interface
if model is not None:
    interface = gr.Interface(
        fn=predict_output,
        inputs=[
            gr.Number(label="Age "),
            gr.Number(label="Gender "),
            gr.Number(label="Education Level "),
            gr.Number(label="Job title "),
            gr.Number(label="Years OF Experience ")
        ],
        outputs="text",
        title="Salary Prediction Module",
        description="Enter feature values to get a prediction from your RandomForestRegressor model."
    )

    # Launch the interface
    interface.launch(debug=True, share=True)

"""First, we need to install `streamlit` if it's not already installed. This will create a new cell to install `streamlit`."""

pip install streamlit



"""Now, let's create the Streamlit application file (`app.py`). This cell will write the Streamlit code to a file named `app.py` in your Colab environment."""

import joblib

# Commented out IPython magic to ensure Python compatibility.
# %%writefile 1app.py
# 
# import streamlit as st
# import joblib
# import numpy as np
# 
# # Define the path to your model
# model_path = '/content/random_forest_regressor_model.joblib'
# 
# # Load the model
# @st.cache_resource
# def load_model():
#     try:
#         model = joblib.load(model_path)
#         return model
#     except FileNotFoundError:
#         st.error(f"Error: Model file not found at {model_path}")
#         return None
# 
# model = load_model()
# 
# st.title("Random Forest Regressor Model 1 Front-end")
# st.write("Enter feature values to get a prediction from your RandomForestRegressor model.")
# 
# # Define a prediction function
# def predict_output(model, feature1, feature2, feature3, feature4, feature5):
#     if model is None:
#         return "Model not loaded. Cannot make prediction."
# 
#     features = np.array([[feature1, feature2, feature3, feature4, feature5]])
# 
#     try:
#         prediction = model.predict(features)
#         return f"Predicted Value: {prediction[0]:.2f}"
#     except Exception as e:
#         return f"Error during prediction: {e}"
# 
# # Create input fields in Streamlit
# st.sidebar.header("Input Features")
# feature1 = st.sidebar.number_input("Age ", value=30.0)
# feature2 = st.sidebar.number_input("Gender ", value=1.0) # Assuming 1 for Male, 0 for Female, or similar encoding
# feature3 = st.sidebar.number_input("Education Level ", value=12.0)
# feature4 = st.sidebar.number_input("Job title ", value=5.0) # Assuming some numerical encoding for job title
# feature5 = st.sidebar.number_input("Years OF Experience ", value=5.0)
# 
# if st.sidebar.button("Predict"):
#     if model is not None:
#         result = predict_output(model, feature1, feature2, feature3, feature4, feature5)
#         st.success(result)
#     else:
#         st.error("Model could not be loaded. Please check the model path.")
#