# -*- coding: utf-8 -*-
"""Module 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1k3ekaYo8HZaZq-6SOX-g1WgisDLxBp
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/Salary_Data.csv')
df

df.isnull().sum()

df.shape

num = df.select_dtypes(include=['int64','float64'])
num.columns

cat = df.select_dtypes(include=['object'])
cat.columns

pd.get_dummies(df)

from sklearn.preprocessing import LabelEncoder

df=pd.read_csv('/content/Salary_Data.csv')
df.fillna(df.mode().iloc[0], inplace=True)

apply = LabelEncoder()
for column in cat.columns:
    df[column] = apply.fit_transform(df[column])
df

x=df.drop(['Salary'],axis=1)
y=df['Salary']

from sklearn.model_selection import train_test_split

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Feature Scaling (optional but recommended for some models)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Data split into training and testing sets.")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

# 1. Linear Regression
print("\n--- Linear Regression ---")
lin_reg_model = LinearRegression()
lin_reg_model.fit(X_train_scaled, y_train)
y_pred_lin_reg = lin_reg_model.predict(X_test_scaled)
mae_lin_reg = mean_absolute_error(y_test, y_pred_lin_reg)
r2_lin_reg = r2_score(y_test, y_pred_lin_reg)
print(f"MAE: {mae_lin_reg:.2f}")
print(f"R-squared: {r2_lin_reg:.2f}")

# 2. Decision Tree Regressor
print("\n--- Decision Tree Regressor ---")
dt_reg_model = DecisionTreeRegressor(random_state=42)
dt_reg_model.fit(X_train, y_train) # Decision trees are not sensitive to scaling
y_pred_dt_reg = dt_reg_model.predict(X_test)
mae_dt_reg = mean_absolute_error(y_test, y_pred_dt_reg)
r2_dt_reg = r2_score(y_test, y_pred_dt_reg)
print(f"MAE: {mae_dt_reg:.2f}")
print(f"R-squared: {r2_dt_reg:.2f}")

# 3. Random Forest Regressor
print("\n--- Random Forest Regressor ---")
rf_reg_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_reg_model.fit(X_train, y_train) # Random forests are not sensitive to scaling
y_pred_rf_reg = rf_reg_model.predict(X_test)
mae_rf_reg = mean_absolute_error(y_test, y_pred_rf_reg)
r2_rf_reg = r2_score(y_test, y_pred_rf_reg)
print(f"MAE: {mae_rf_reg:.2f}")
print(f"R-squared: {r2_rf_reg:.2f}")

# 4. Gradient Boosting Regressor
print("\n--- Gradient Boosting Regressor ---")
gb_reg_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
gb_reg_model.fit(X_train, y_train) # Gradient boosting is not sensitive to scaling
y_pred_gb_reg = gb_reg_model.predict(X_test)
mae_gb_reg = mean_absolute_error(y_test, y_pred_gb_reg)
r2_gb_reg = r2_score(y_test, y_pred_gb_reg)
print(f"MAE: {mae_gb_reg:.2f}")
print(f"R-squared: {r2_gb_reg:.2f}")

import joblib

# Assuming rf_reg_model is the best model (Random Forest Regressor)
model_filename = 'random_forest_regressor_model.joblib'
joblib.dump(rf_reg_model, model_filename)

print(f"Best model (Random Forest Regressor) saved as {model_filename}")

